### ISSUE TITLE
Send html and text variant in one mail

### ISSUE THREAD

**Issue by Vampire** [git-multimail/git-multimail#196] opened 2018-08-23 11:16 UTC
When sending html mails, you can send them as multipart mails, providing the html version and the text version, then MUAs that support html can display html and MUAs that don't support it can show the text version.

It would be nice if git-multimail would send both variants if html is enabled.

**Comment by moy** [comment] 2018-08-23 11:18
Duplicate of #176. Unfortunately, I don't think it's very simple to implement (clearly doable, though).

**Closed by moy** 2018-08-23 11:18 UTC
